modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
logoFile = "${mod_icon}"

[[dependencies.rockreactors]]
modId = "neoforge"
type = "required"
versionRange = "${mod_neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.rockreactors]]
modId = "minecraft"
type = "required"
versionRange = "${mod_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "rockreactors.mixins.json"

[[mixins]]
config = "rockreactors-neoforge.mixins.json"
